# Generated by Django 4.1.1 on 2022-09-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0003_project_end_date_project_p_status_project_start_date_and_more",
        ),
        ("timelogging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprojectdailylogs",
            name="user_project_role",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.userprojectrole",
            ),
            preserve_default=False,
        ),
    ]
