# Generated by Django 4.1.1 on 2022-09-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timelogging", "0002_userprojectdailylogs_user_project_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdailylogs",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprojectdailylogs",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
