# Generated by Django 4.1.1 on 2022-09-07 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_userprojectrole_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="p_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Live", "Project Ongoing"),
                    ("Completed", "Project Completed"),
                    ("Pipeline", "Project Pending Start"),
                    ("Hiatus", "Project On-Hold"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="p_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WEB", "Website Development"),
                    ("ML", "Machine Learning"),
                    ("DS", "Data Science/Engineering"),
                    ("RE", "Robotics & Engineering"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
