# Generated by Django 4.1.1 on 2022-09-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0003_project_end_date_project_p_status_project_start_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_dashboard_key",
            field=models.CharField(default="420-666", max_length=150),
        ),
    ]
